on:
  push: 

jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - name: curl branches
        run: |
          curl -L \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            "https://api.github.com/repos/Ethereal-Services/repoinfo/branches"
          echo ----
          curl -L \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/Ethereal-Services/repoinfo/commits/f2b5e3d42f0314dacc664405cd75a16246806019

      - name: curl team
        run: |
          curl -L \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.test }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/orgs/Ethereal-Services/teams/test/members

      - name: curl env (NOT WORKING)
        run: |
          curl -L \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/Ethereal-Services/repoinfo/environments/dev/deployment_protection_rules

      - name: get env only
        run: |
          curl -L \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/Ethereal-Services/repoinfo/environments/dev

      - name: get last commit to codeowners
        run: |
          curl -s "https://api.github.com/repos/Ethereal-Services/repoinfo/commits?path=.github/CODEOWNERS&page=1&per_page=1" #| \
           # jq -r '.[0].commit.committer.date'

      - name: get codeowners list
        run: |
          curl -L \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/Ethereal-Services/repoinfo/contents/.github/CODEOWNERS | \
            jq -r '.content'
          VALUE=$(curl -L \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/Ethereal-Services/repoinfo/contents/.github/CODEOWNERS | \
            jq -r '.content')
          echo $VALUE | base64 --decode  
      
      - name: get latest tag (NOT WORKING)
        run: |
          curl -L \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/Ethereal-Services/repoinfo/git/tags/latest

      - name: get latest release
        run: |
          curl -L \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/Ethereal-Services/repoinfo/releases/latest

      - name: get amount of alerts
        run: |
          curl -L \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.test }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/Ethereal-Services/repoinfo/code-scanning/alerts

      - name: get pull requests
        run: |  
          curl -L \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/Ethereal-Services/repoinfo/pulls
