on:
  push: 

jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - name: curl
        run: |
          curl -L \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${secrets.GITHUB_TOKEN}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/Ethereal-Services/repoinfo/branches
