on:
  push: 

jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - name: curl
        run: |
          curl -I -L \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{secrets.test}}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            "https://api.github.com/repos/Ethereal-Services/repoinfo/branches?per_page=1"
